#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Start builds on tags only
#skip_non_tags: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      QT_Ver: 5.6
      MSVC_Compiler: msvc2015
      MSVC_Name: Microsoft Visual Studio 14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QT_Ver: 5.12
      MSVC_Compiler: msvc2017
      MSVC_Name: Microsoft Visual Studio 14.0

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds

  # MSBuild verbosity level
  verbosity: detailed

init:
  - appveyor UpdateBuild -Version %APPVEYOR_REPO_COMMIT%

install:
  # Submodules
  - git submodule update --init --recursive

  # MSVC Paths
  # https://www.appveyor.com/docs/lang/cpp/#visual-studio
  - call "C:\Program Files (x86)\%MSVC_Name%\VC\vcvarsall.bat" x86

  # QT Paths
  # https://www.appveyor.com/docs/build-environment/#qt
  - set QTDIR=C:\Qt\%QT_Ver%\%MSVC_Compiler%
  - set PATH=%PATH%;%QTDIR%\bin

  # NSIS Paths
  # https://www.appveyor.com/docs/build-environment/#tools
  - set PATH=%PATH%;C:\Program Files (x86)\NSIS

  # NSIS Plugin (SimpleFC)
  - appveyor DownloadFile http://nsis.sourceforge.net/mediawiki/images/d/d7/NSIS_Simple_Firewall_Plugin_1.20.zip
  - 7z e NSIS_Simple_Firewall_Plugin_1.20.zip -o"C:\Program Files (x86)\NSIS\Plugins\x86-ansi" SimpleFC.dll

build_script:
  - qmake
  - nmake

artifacts:
  - path: install\win\*.exe
  - path: release\*.pdb
